name: Deploy SWA

on:
  workflow_call:
    inputs:
      web_dir:
        type: string
        default: web
      swa_name:
        type: string
        default: lc-swa-web
      swa_token:
        type: string
        required: true
    # no Azure login is strictly required for the SWA deploy action when using deployment token

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: ${{ inputs.web_dir }}
          skip_app_build: false
          api_location: ""
          deployment_token: ${{ inputs.swa_token }}
